on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**" # matches every branch
name: "Continuous Integration"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run build
      - run: npm run lint
      - run: npm run format
